insert into t_user(user_name, password) values ('david@gmail.com1','$2a$11$rNWkw3/XMOyJZzjxxUSNQuX.GnQpoqWfq4.yP7t0wkUAaO7NFXQte');
insert into t_group(group_code, group_name) values ('LEVEL_01','Level 01');
insert into t_group(group_code, group_name) values ('LEVEL_02','Level 02');
insert into t_group(group_code, group_name) values ('LEVEL_03','Level 03');
insert into t_group(group_code, group_name) values ('LEVEL_04','Level 04');
insert into t_group(group_code, group_name) values ('LEVEL_ADMIN','Level Admin');
insert into t_role(role_code, role_name, fk_group) values ('ROLE_LEVEL_01','Role Level 01', 1);
insert into t_role(role_code, role_name, fk_group) values ('ROLE_LEVEL_02','Role Level 02', 2);
insert into t_role(role_code, role_name, fk_group) values ('ROLE_LEVEL_03','Role Level 03', 3);
insert into t_role(role_code, role_name, fk_group) values ('ROLE_LEVEL_04','Role Level 04', 4);
insert into t_role(role_code, role_name, fk_group) values ('ROLE_LEVEL_ADMIN','Role Level Admin', 5);