export const SIGN_IN='SIGN_IN';
export const SIGN_OUT ='SIGN_OUT';
export const CREATE_INVOICE = 'CREATE_INVOICE';
export const IS_INVOICE_CREATED = 'IS_INVOICE_CREATED';
export const FETCH_INVOICES = 'FETCH_INVOICES';
export const FETCH_INVOICE = 'FETCH_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const EDIT_INVOICE = 'EDIT_INVOICE';

export const ADD_INVOICEITEMS = 'ADD_INVOICEITEMS';
export const EDIT_INVOICEITEMS = 'EDIT_INVOICEITEMS';
export const DELETE_INVOICEITEMS = 'DELETE_INVOICEITEMS';
